'use client';
import { useEffect,useRef,useState } from 'react';
import { ArrowUpRight, BarChart3, Check, Copy, FileText, ImagePlus, LogOut, Plus, Save, Search, ShieldCheck, Trash2, X } from 'lucide-react';
import type { ManagedArticle } from '@/lib/news-store';
import './admin-console.css';
type Stats={days:number;totals:{views:number;sessions:number;today:number};daily:{day:string;views:number}[];pages:{path:string;views:number}[];devices:{device:string;views:number}[];referrers:{referrer:string;views:number}[];published:{published:number}};
const date=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});
const blank=():ManagedArticle=>({slug:'',title:'',category:'公司动态',summary:'',cover:'',status:'draft',publishedAt:date(),updatedAt:'',version:0,sections:[{title:'',text:''}],source:{title:'',publisher:'',url:''}});
const statuses={draft:'草稿',published:'已发布',offline:'已下架'};
async function api<T={articles:ManagedArticle[];url:string}>(path:string,options:RequestInit={}):Promise<T> {const r=await fetch(`/api/admin/${path}`,options);let body:T & {error?:string};try{body=await r.json() as T & {error?:string};}catch{throw new Error('服务器响应异常，请稍后重试');}if(!r.ok)throw new Error(body.error||'操作失败');return body;}
const json=(body:unknown,method='POST')=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
export default function AdminConsole(){
  const [auth,setAuth]=useState<'checking'|'login'|'ready'>('checking');
  const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [tab,setTab]=useState<'news'|'stats'>('news');const [articles,setArticles]=useState<ManagedArticle[]>([]);
  const [loaded,setLoaded]=useState(false);const [search,setSearch]=useState('');const [status,setStatus]=useState('all');
  const [draft,setDraft]=useState<ManagedArticle|null>(null);const [dirty,setDirty]=useState(false);const [preview,setPreview]=useState(false);
  const [uploading,setUploading]=useState(false);const [stats,setStats]=useState<Stats|null>(null);const [days,setDays]=useState('30');
  const editor=useRef<HTMLFormElement>(null);
  useEffect(()=>{void api('session').then(()=>setAuth('ready')).catch(()=>setAuth('login'));},[]);
  useEffect(()=>{if(auth==='ready')void loadArticles();},[auth]);
  useEffect(()=>{if(auth==='ready'&&tab==='stats'){setStats(null);setError('');void api<Stats>(`stats?days=${days}`).then(setStats).catch(e=>setError(e.message));}},[auth,tab,days]);
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  async function loadArticles(){try{const result=await api('news');setArticles(result.articles);setLoaded(true);}catch(e){setError((e as Error).message);}}
  function change(patch:Partial<ManagedArticle>){setDraft(d=>d?{...d,...patch}:d);setDirty(true);setNotice('');}
  function open(article:ManagedArticle|null){if(dirty&&!confirm('当前修改尚未保存，确认放弃？'))return;setDraft(article?structuredClone(article):blank());setDirty(false);setPreview(false);setError('');setNotice('');}
  function close(){if(dirty&&!confirm('当前修改尚未保存，确认放弃？'))return;setDraft(null);setDirty(false);setError('');}
  async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('login',json({password}));setPassword('');setAuth('ready');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function logout(){if(dirty&&!confirm('当前修改尚未保存，仍要退出？'))return;try{await api('logout',json({}));setAuth('login');setDraft(null);setDirty(false);}catch(e){setError((e as Error).message);}}
  async function save(nextStatus:ManagedArticle['status']) {
    if(!draft||!editor.current?.reportValidity())return;
    setBusy(true);setError('');setNotice('');
    try{await api(draft.version?`news/${draft.slug}`:'news',json({...draft,status:nextStatus},draft.version?'PUT':'POST'));const result=await api('news');setArticles(result.articles);setDraft(result.articles.find((a:ManagedArticle)=>a.slug===draft.slug)??null);setDirty(false);setNotice(nextStatus==='published'?'文章已保存并发布，前台即时生效':nextStatus==='offline'?'文章已下架，前台不再展示':'草稿已保存');}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  async function remove(article:ManagedArticle){if(!confirm(`永久删除《${article.title}》？此操作无法撤销；如只需隐藏，请选择下架。`))return;setBusy(true);setError('');try{await api(`news/${article.slug}`,json({version:article.version},'DELETE'));setDraft(null);setDirty(false);await loadArticles();setNotice('文章已删除');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function upload(file:File|undefined){if(!file)return;if(file.size>8*1024*1024){setError('图片不能超过 8 MB');return;}setUploading(true);setError('');try{const result=await api('upload',{method:'POST',headers:{'Content-Type':file.type},body:file});change({cover:result.url});setNotice('封面已上传至对象存储，请保存文章');}catch(e){setError((e as Error).message);}finally{setUploading(false);}}
  if(auth==='checking')return <main className="admin-root admin-login"><p>正在检查登录状态…</p></main>;
  if(auth==='login')return <main className="admin-root admin-login"><div className="admin-login-brand"><ShieldCheck size={36}/><span>壹消网站管理</span></div><form onSubmit={login} className="admin-login-form"><p className="admin-subtitle">仅限授权管理员</p><h1>登录内容后台</h1><p>管理新闻发布，查看网站访问情况。</p><label>管理员密码<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} /></label>{error&&<p className="admin-error" role="alert">{error}</p>}<button className="admin-primary" disabled={busy}>{busy?'正在登录…':'登录后台'}</button><a href="/">返回网站</a></form></main>;
  const filtered=articles.filter(a=>(status==='all'||a.status===status)&&`${a.title} ${a.category}`.includes(search));
  return <div className="admin-root admin-app">
    <aside className="admin-sidebar"><a className="admin-brand" href="/admin"><ShieldCheck/><span>壹消<b>网站内容管理</b></span></a><nav aria-label="管理导航"><button className={tab==='news'?'active':''} onClick={()=>{if(draft)close();if(!dirty)setTab('news');}}><FileText size={19}/>新闻管理<span>{articles.length}</span></button><button className={tab==='stats'?'active':''} onClick={()=>{if(dirty&&!confirm('放弃未保存的修改？'))return;setDirty(false);setDraft(null);setTab('stats');}}><BarChart3 size={19}/>访问统计</button></nav><div className="admin-sidebar-foot"><a href="/" target="_blank" rel="noreferrer">打开网站 <ArrowUpRight size={16}/></a><button onClick={logout}><LogOut size={16}/>退出登录</button></div></aside>
    <main className="admin-main"><header className="admin-topbar"><span>壹壹壹壹（北京）安全技术有限公司</span><span>管理员</span></header>
      <div className="admin-workspace">{error&&<div className="admin-error" role="alert">{error}<button onClick={()=>{setError('');if(!draft)void loadArticles();}}>重试</button></div>}{notice&&<output className="admin-success"><Check size={17}/>{notice}</output>}
      {tab==='news'&&!draft&&<><div className="admin-page-heading"><div><h1>新闻管理</h1><p>编辑内容、上传封面，管理新闻的展示状态。</p></div><button className="admin-primary" onClick={()=>open(null)}><Plus size={18}/>新建文章</button></div>
        <div className="admin-toolbar"><div className="admin-filters">{[['all','全部'],['published','已发布'],['draft','草稿'],['offline','已下架']].map(([v,label])=><button key={v} className={status===v?'selected':''} onClick={()=>setStatus(v)}>{label}<span>{v==='all'?articles.length:articles.filter(a=>a.status===v).length}</span></button>)}</div><label className="admin-search"><Search size={18}/><input placeholder="搜索标题或分类" aria-label="搜索新闻" value={search} onChange={e=>setSearch(e.target.value)} /></label></div>
        <div className="admin-table-wrap"><table><thead><tr><th>文章</th><th>状态</th><th>发布日期</th><th>操作</th></tr></thead><tbody>{filtered.map(a=><tr key={a.slug}><td><button className="admin-article-title" onClick={()=>open(a)}>{a.cover&&<img src={a.cover} alt=""/>}<span><strong>{a.title}</strong><small>{a.category} · /news/{a.slug}</small></span></button></td><td><span className={`admin-badge ${a.status}`}>{statuses[a.status]}</span></td><td>{a.publishedAt}</td><td><button className="admin-text-button" onClick={()=>open(a)}>编辑</button>{a.status==='published'&&<a href={`/news/${a.slug}`} target="_blank" rel="noreferrer" className="admin-text-button">查看</a>}</td></tr>)}</tbody></table>{(!loaded||!filtered.length)&&<div className="admin-empty">{!loaded?'正在加载文章…':search?'没有匹配的文章，请换个关键词。':'暂无文章，点击“新建文章”开始。'}</div>}</div>
        <p className="admin-hint">草稿和已下架文章不会显示在前台；图片由对象存储直接提供，网站不转发图片流量。</p></>}
      {tab==='news'&&draft&&<><div className="admin-page-heading"><div><button className="admin-text-button" onClick={close}>返回新闻列表</button><h1>{draft.version?'编辑文章':'新建文章'}<span className={`admin-badge ${draft.status}`}>{dirty?'未保存':statuses[draft.status]}</span></h1></div><div className="admin-editor-actions"><button onClick={()=>setPreview(!preview)}>{preview?'继续编辑':'预览排版'}</button><button className="admin-primary" disabled={busy||uploading} onClick={()=>void save(draft.status)}><Save size={17}/>{busy?'保存中…':'保存修改'}</button></div></div>
        <form ref={editor} onSubmit={e=>{e.preventDefault();void save(draft.status);}} className="admin-editor">
          <div className="admin-editor-body">{preview?<article className="admin-preview"><span>{draft.category} · {draft.publishedAt}</span><h2>{draft.title||'文章标题'}</h2><p>{draft.summary}</p>{draft.cover&&<img src={draft.cover} alt="封面预览"/>}{draft.sections.map((s,i)=><section key={i}><h3>{s.title}</h3><p>{s.text}</p></section>)}<p>{draft.source.publisher}</p></article>:<><label>文章标题<input autoFocus required maxLength={160} placeholder="输入清晰、具体的新闻标题" value={draft.title} onChange={e=>change({title:e.target.value})}/></label><label>内容摘要<textarea required maxLength={1000} rows={3} placeholder="概括文章要点，用于新闻列表和搜索摘要。" value={draft.summary} onChange={e=>change({summary:e.target.value})}/></label><div className="admin-field-heading"><h2>文章正文</h2><span>按小标题分段编辑</span></div>{draft.sections.map((s,i)=><fieldset key={i} className="admin-section-editor"><legend>段落 {i+1}</legend><label>小标题<input required maxLength={160} value={s.title} onChange={e=>change({sections:draft.sections.map((x,j)=>j===i?{...x,title:e.target.value}:x)})}/></label><label>正文<textarea required rows={7} maxLength={20000} value={s.text} onChange={e=>change({sections:draft.sections.map((x,j)=>j===i?{...x,text:e.target.value}:x)})}/></label>{draft.sections.length>1&&<button type="button" className="admin-text-button" onClick={()=>change({sections:draft.sections.filter((_,j)=>j!==i)})}><Trash2 size={15}/>删除此段</button>}</fieldset>)}<button type="button" disabled={draft.sections.length>=40} onClick={()=>change({sections:[...draft.sections,{title:'',text:''}]})}><Plus size={17}/>增加段落</button></>}</div>
          <aside className="admin-editor-settings"><section><h2>发布设置</h2><label>分类<input required maxLength={40} list="news-categories" value={draft.category} onChange={e=>change({category:e.target.value})}/><datalist id="news-categories"><option>公司动态</option><option>行业解读</option><option>设备科普</option><option>项目动态</option></datalist></label><label>发布日期<input required type="date" value={draft.publishedAt} onChange={e=>change({publishedAt:e.target.value})}/></label><label>文章地址<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={100} readOnly={!!draft.version} placeholder="例如 smart-fire-news" value={draft.slug} onChange={e=>change({slug:e.target.value})}/><small>小写英文、数字、短横线；创建后不可更改。</small></label><button type="button" disabled={busy||uploading} className="admin-primary" onClick={()=>void save('published')}>{draft.status==='published'?'保存并保持发布':'发布文章'}</button>{draft.status==='published'?<button type="button" disabled={busy} onClick={()=>void save('offline')}>下架文章</button>:<button type="button" disabled={busy||uploading} onClick={()=>void save('draft')}>保存为草稿</button>}<p className="admin-hint">选择未来日期的已发布文章，将在该日期（北京时间）开始展示。</p></section>
          <section><h2>新闻封面</h2>{draft.cover?<div className="admin-cover-preview"><img src={draft.cover} alt="新闻封面"/><button type="button" aria-label="移除封面" onClick={()=>change({cover:''})}><X size={16}/></button></div>:<div className="admin-cover-empty"><ImagePlus size={28}/><span>添加一张新闻封面</span></div>}<label className="admin-upload">{uploading?'正在上传并检查外链…':'选择图片上传'}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={uploading} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><p className="admin-hint">JPG、PNG、WebP、GIF，最大 8 MB。上传后请保存文章。</p>{draft.cover&&<button type="button" className="admin-text-button" onClick={()=>void navigator.clipboard.writeText(draft.cover).then(()=>setNotice('图片外链已复制')).catch(()=>setError('无法复制，请从封面地址手动复制'))}><Copy size={15}/>复制图片外链</button>}</section>
          <section><h2>参考来源（选填）</h2><label>来源名称<input maxLength={200} value={draft.source.publisher} onChange={e=>change({source:{...draft.source,publisher:e.target.value}})}/></label><label>来源标题<input maxLength={200} value={draft.source.title} onChange={e=>change({source:{...draft.source,title:e.target.value}})}/></label><label>原文链接<input type="url" placeholder="https://" value={draft.source.url} onChange={e=>change({source:{...draft.source,url:e.target.value}})}/></label></section>{!!draft.version&&<button type="button" className="admin-danger" disabled={busy} onClick={()=>void remove(draft)}><Trash2 size={16}/>永久删除文章</button>}</aside>
        </form></>}
      {tab==='stats'&&<><div className="admin-page-heading"><div><h1>访问统计</h1><p>了解哪些页面正在被阅读。数据来自网站真实访问。</p></div><label className="admin-period">统计范围<select value={days} onChange={e=>setDays(e.target.value)}><option value="7">最近 7 天</option><option value="30">最近 30 天</option></select></label></div>{!stats?<div className="admin-empty">{error?'统计暂时不可用':'正在读取统计…'}</div>:<><div className="admin-metrics">{[['页面浏览量',stats.totals.views,'PV · 所选时间范围'],['访问会话',stats.totals.sessions,'同一标签页会话去重'],['今日浏览量',stats.totals.today,'北京时间'],['已发布文章',stats.published.published,'前台可阅读']].map(([label,value,hint])=><section key={String(label)}><p>{label}</p><strong>{Number(value).toLocaleString()}</strong><span>{hint}</span></section>)}</div><section className="admin-stats-panel"><h2>每日浏览趋势</h2>{stats.daily.length?<div className="admin-chart" aria-label="每日页面浏览量">{Array.from({length:Number(days)},(_,i)=>{const day=new Date(Date.now()-(Number(days)-1-i)*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});const views=stats.daily.find(d=>d.day===day)?.views||0;return <div key={day} title={`${day}：${views} 次浏览`}><span>{views||''}</span><i style={{height:`${views/Math.max(1,...stats.daily.map(d=>d.views))*150}px`}}/><small>{i%Math.ceil(Number(days)/7)===0?day.slice(5):''}</small></div>;})}</div>:<div className="admin-empty">暂无访问记录。访客打开网站后，这里会出现真实数据。</div>}</section><div className="admin-stats-grid"><section className="admin-stats-panel"><h2>热门页面</h2>{stats.pages.length?<table><thead><tr><th>页面路径</th><th>浏览量</th></tr></thead><tbody>{stats.pages.map(p=><tr key={p.path}><td><a href={p.path} target="_blank" rel="noreferrer">{p.path}</a></td><td>{p.views}</td></tr>)}</tbody></table>:<p className="admin-hint">暂无数据</p>}</section><div><section className="admin-stats-panel"><h2>访问设备</h2>{stats.devices.map(d=><div className="admin-stat-row" key={d.device}><span>{d.device}</span><strong>{d.views}</strong></div>)}{!stats.devices.length&&<p className="admin-hint">暂无数据</p>}</section><section className="admin-stats-panel"><h2>访问来源</h2>{stats.referrers.map(r=><div className="admin-stat-row" key={r.referrer}><span>{r.referrer}</span><strong>{r.views}</strong></div>)}{!stats.referrers.length&&<p className="admin-hint">暂无数据</p>}</section></div></div></>}<p className="admin-hint">记录保留 90 天；不保存原始 IP，不统计后台页面，尊重浏览器“不跟踪”设置。会话数不是实名人数，拦截脚本的访问可能不计入。</p></>}
      </div></main>
  </div>;
}
